/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FeedbackEscrow {
  export type CampaignStruct = {
    creator: AddressLike;
    totalDeposit: BigNumberish;
    endDate: BigNumberish;
    numAspects: BigNumberish;
    status: BigNumberish;
  };

  export type CampaignStructOutput = [
    creator: string,
    totalDeposit: bigint,
    endDate: bigint,
    numAspects: bigint,
    status: bigint
  ] & {
    creator: string;
    totalDeposit: bigint;
    endDate: bigint;
    numAspects: bigint;
    status: bigint;
  };
}

export interface FeedbackEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EMERGENCY_DELAY"
      | "EMERGENCY_PENALTY_BPS"
      | "authorizedBackend"
      | "campaigns"
      | "createCampaign"
      | "distributePayments"
      | "emergencyWithdraw"
      | "getCampaign"
      | "owner"
      | "setAuthorizedBackend"
      | "setTreasury"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "CampaignFinalized"
      | "EmergencyWithdraw"
      | "PaymentDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EMERGENCY_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_PENALTY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedBackend",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "campaigns", values: [string]): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributePayments",
    values: [
      string,
      AddressLike[],
      BigNumberish[],
      BigNumberish[],
      string[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getCampaign", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedBackend",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "EMERGENCY_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_PENALTY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedBackend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributePayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedBackend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: string,
    creator: AddressLike,
    totalDeposit: BigNumberish,
    endDate: BigNumberish,
    numAspects: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    creator: string,
    totalDeposit: bigint,
    endDate: bigint,
    numAspects: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    creator: string;
    totalDeposit: bigint;
    endDate: bigint;
    numAspects: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFinalizedEvent {
  export type InputTuple = [
    campaignId: string,
    totalPaidToWinners: BigNumberish,
    refundToCreator: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    totalPaidToWinners: bigint,
    refundToCreator: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    totalPaidToWinners: bigint;
    refundToCreator: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    campaignId: string,
    creator: AddressLike,
    creatorAmount: BigNumberish,
    treasuryAmount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    creator: string,
    creatorAmount: bigint,
    treasuryAmount: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    creator: string;
    creatorAmount: bigint;
    treasuryAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentDistributedEvent {
  export type InputTuple = [
    campaignId: string,
    wallet: AddressLike,
    amount: BigNumberish,
    score: BigNumberish,
    aspect: string
  ];
  export type OutputTuple = [
    campaignId: string,
    wallet: string,
    amount: bigint,
    score: bigint,
    aspect: string
  ];
  export interface OutputObject {
    campaignId: string;
    wallet: string;
    amount: bigint;
    score: bigint;
    aspect: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeedbackEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): FeedbackEscrow;
  waitForDeployment(): Promise<this>;

  interface: FeedbackEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EMERGENCY_DELAY: TypedContractMethod<[], [bigint], "view">;

  EMERGENCY_PENALTY_BPS: TypedContractMethod<[], [bigint], "view">;

  authorizedBackend: TypedContractMethod<[], [string], "view">;

  campaigns: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, bigint, bigint] & {
        creator: string;
        totalDeposit: bigint;
        endDate: bigint;
        numAspects: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [
      campaignId: string,
      endDate: BigNumberish,
      numAspects: BigNumberish,
      totalAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  distributePayments: TypedContractMethod<
    [
      campaignId: string,
      winners: AddressLike[],
      amounts: BigNumberish[],
      scores: BigNumberish[],
      aspects: string[],
      refundToCreator: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [campaignId: string],
    [void],
    "nonpayable"
  >;

  getCampaign: TypedContractMethod<
    [campaignId: string],
    [FeedbackEscrow.CampaignStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAuthorizedBackend: TypedContractMethod<
    [_newBackend: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EMERGENCY_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_PENALTY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizedBackend"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, bigint, bigint] & {
        creator: string;
        totalDeposit: bigint;
        endDate: bigint;
        numAspects: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      campaignId: string,
      endDate: BigNumberish,
      numAspects: BigNumberish,
      totalAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributePayments"
  ): TypedContractMethod<
    [
      campaignId: string,
      winners: AddressLike[],
      amounts: BigNumberish[],
      scores: BigNumberish[],
      aspects: string[],
      refundToCreator: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[campaignId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: string],
    [FeedbackEscrow.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedBackend"
  ): TypedContractMethod<[_newBackend: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFinalized"
  ): TypedContractEvent<
    CampaignFinalizedEvent.InputTuple,
    CampaignFinalizedEvent.OutputTuple,
    CampaignFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "PaymentDistributed"
  ): TypedContractEvent<
    PaymentDistributedEvent.InputTuple,
    PaymentDistributedEvent.OutputTuple,
    PaymentDistributedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(string,address,uint256,uint256,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignFinalized(string,uint256,uint256)": TypedContractEvent<
      CampaignFinalizedEvent.InputTuple,
      CampaignFinalizedEvent.OutputTuple,
      CampaignFinalizedEvent.OutputObject
    >;
    CampaignFinalized: TypedContractEvent<
      CampaignFinalizedEvent.InputTuple,
      CampaignFinalizedEvent.OutputTuple,
      CampaignFinalizedEvent.OutputObject
    >;

    "EmergencyWithdraw(string,address,uint256,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "PaymentDistributed(string,address,uint256,uint256,string)": TypedContractEvent<
      PaymentDistributedEvent.InputTuple,
      PaymentDistributedEvent.OutputTuple,
      PaymentDistributedEvent.OutputObject
    >;
    PaymentDistributed: TypedContractEvent<
      PaymentDistributedEvent.InputTuple,
      PaymentDistributedEvent.OutputTuple,
      PaymentDistributedEvent.OutputObject
    >;
  };
}
